spring:
  application:
    name: calorie-counter
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}