springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  application:
    name: calorie-counter
  datasource:
    url: jdbc:postgresql://rc1d-c4hspa1jrzrfrbl3.mdb.yandexcloud.net:6432/test-app-db?targetServerType=master&ssl=true&sslmode=verify-full
    properties:
      ssl: true
      sslMode: VERIFY_CA